---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsuser2
  namespace: nsuser2

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nsuser2-full-access
  namespace: nsuser2
rules:
- apiGroups: ["", "extensions", "apps","litmuschaos.io","rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nsuser2-view
  namespace: nsuser2
subjects:
- kind: ServiceAccount
  name: nsuser2
  namespace: nsuser2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nsuser2-full-access
