---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus
  labels:
    name: litmus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: litmus
  labels:
    name: litmus
rules:
  - apiGroups: ["","apps","batch","litmuschaos.io","apps.openshift.io"]
    resources: ["pods","jobs","deployments","replicationcontrollers","daemonsets","replicasets","deploymentconfigs","statefulsets","events","configmaps","services","secrets","chaosengines","chaosexperiments","chaosresults"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get","create","list","delete","update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: litmus
  labels:
    name: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus
subjects:
  - kind: ServiceAccount
    name: litmus
    namespace: nsuser2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-operator-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-operator
  template:
    metadata:
      labels:
        name: chaos-operator
    spec:
      serviceAccountName: litmus
      containers:
        - name: chaos-operator
          image: litmuschaos/chaos-operator:1.5.0
          command:
            - chaos-operator
          imagePullPolicy: Always
          env:
            - name: CHAOS_RUNNER_IMAGE
              value: "litmuschaos/chaos-runner:1.5.0"
            - name: WATCH_NAMESPACE
              value: nsuser2
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaos-operator"


